apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: w0onll29u-nodejs 
  janus-idp.io/tekton: w0onll29u-nodejs
  backstage.io/kubernetes-id: w0onll29u-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w0onll29u-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  