apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: w0onll29u-nodejs-gitops
  description: This is GitOps manifest for w0onll29u-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: w0onll29u-nodejs
    backstage.io/kubernetes-id: w0onll29u-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: w0onll29u-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:w0onll29u-nodejs
